// Package proxy generates configuration for the Velocity Minecraft proxy
// from an mc-operator Manifest. Keeping this as its own package (not under
// internal/) means a user could import it to build velocity.toml files from
// their own manifests without running the full daemon.
package proxy

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sort"
	"text/template"

	"github.com/devvelvet/mc-operator/pkg/mctypes"
)

// VelocityConfig is the minimal subset of velocity.toml fields mc-operator manages.
// Fields outside this struct are preserved by the user — the daemon only writes
// the files under its own management and does not parse the user's existing toml.
type VelocityConfig struct {
	Bind                     string            // "0.0.0.0:25565"
	MOTD                     string            // MiniMessage-formatted MOTD
	ShowMaxPlayers           int
	OnlineMode               bool
	ForwardingMode           string            // "modern" | "legacy" | "bungeeguard" | "none"
	ForwardingSecret         string            // used when ForwardingMode == "modern"
	Servers                  map[string]string // name -> host:port (as seen from the proxy)
	Try                      []string          // initial connection order
}

// TOML renders cfg to a velocity.toml byte slice.
func (cfg VelocityConfig) TOML() ([]byte, error) {
	if cfg.Bind == "" {
		return nil, fmt.Errorf("velocity config: bind is required")
	}
	if cfg.ForwardingMode == "" {
		cfg.ForwardingMode = "modern"
	}
	if cfg.MOTD == "" {
		cfg.MOTD = "<bold><aqua>mc-operator</aqua></bold> <gray>managed network</gray>"
	}
	if cfg.ShowMaxPlayers == 0 {
		cfg.ShowMaxPlayers = 100
	}

	// Stable ordering so the file is reproducible.
	names := make([]string, 0, len(cfg.Servers))
	for n := range cfg.Servers {
		names = append(names, n)
	}
	sort.Strings(names)
	type entry struct {
		Name string
		Addr string
	}
	data := struct {
		Cfg     VelocityConfig
		Entries []entry
	}{Cfg: cfg}
	for _, n := range names {
		data.Entries = append(data.Entries, entry{Name: n, Addr: cfg.Servers[n]})
	}

	t, err := template.New("velocity").Parse(velocityTmpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const velocityTmpl = `# Auto-generated by mc-operator/pkg/proxy. Do not edit by hand.
# Changes to this file will be overwritten on the next reconcile.

config-version = "2.7"
bind = "{{.Cfg.Bind}}"
motd = "{{.Cfg.MOTD}}"
show-max-players = {{.Cfg.ShowMaxPlayers}}
online-mode = {{.Cfg.OnlineMode}}
player-info-forwarding-mode = "{{.Cfg.ForwardingMode}}"
forwarding-secret-file = "forwarding.secret"

[servers]
{{range .Entries}}{{.Name}} = "{{.Addr}}"
{{end}}
try = [{{range $i, $n := .Cfg.Try}}{{if $i}}, {{end}}"{{$n}}"{{end}}]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 3000
connection-timeout = 5000
read-timeout = 30000
haproxy-protocol = false
tcp-fast-open = false
bungee-plugin-message-channel = true
show-ping-requests = false
failover-on-unexpected-server-disconnect = true
announce-proxy-commands = true
log-command-executions = false
log-player-connections = true

[query]
enabled = false
port = 25577
map = "mc-operator"
show-plugins = false
`

// FromManifest builds a VelocityConfig from a Manifest. Server addresses are
// constructed as "{container-name}:25565" because mc-operator always puts
// servers on a shared Docker network where container name == DNS name.
//
// If m.Proxy.Enabled is false, FromManifest returns an error.
func FromManifest(m *mctypes.Manifest) (VelocityConfig, error) {
	if m == nil {
		return VelocityConfig{}, fmt.Errorf("manifest is nil")
	}
	if !m.Proxy.Enabled {
		return VelocityConfig{}, fmt.Errorf("proxy is not enabled in manifest")
	}
	cfg := VelocityConfig{
		Bind:           fmt.Sprintf("0.0.0.0:%d", m.Proxy.ExternalPort),
		ForwardingMode: defaultStr(m.Proxy.ForwardingMode, "modern"),
		OnlineMode:     true,
		Servers:        map[string]string{},
	}
	for _, s := range m.Servers {
		if s.Type.IsProxy() {
			continue
		}
		cfg.Servers[s.Name] = fmt.Sprintf("%s:25565", s.Name)
	}
	// First non-proxy server is the default landing point.
	for _, s := range m.Servers {
		if !s.Type.IsProxy() {
			cfg.Try = []string{s.Name}
			break
		}
	}
	return cfg, nil
}

func defaultStr(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

// GenerateForwardingSecret returns a cryptographically-random secret suitable
// for velocity.toml's modern forwarding mode. Callers should persist this
// alongside the proxy container's bind mount so it survives restarts.
func GenerateForwardingSecret() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
