// Package mcimage builds Docker images for Minecraft servers from a
// declarative spec. It can be consumed standalone as a library
// (e.g. by cmd/mc-imagegen) or by the mc-operator GitOps daemon.
package mcimage

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/devvelvet/mc-operator/pkg/mctypes"
)

// BuildSpec is everything needed to produce a Minecraft server image.
// It is decoupled from mctypes.ServerSpec so imagegen can be driven
// from CLI flags without a full manifest.
type BuildSpec struct {
	Type       mctypes.ServerType
	Version    string
	MemoryMB   int
	ServerJAR  string // path to the server jar inside the build context
	PluginJARs []string
	// ExtraFiles are additional files to COPY into /server (key=destination, value=source path in context).
	ExtraFiles map[string]string
	// BaseImage overrides the default JRE base image.
	BaseImage string
}

func (b BuildSpec) validate() error {
	if !b.Type.Known() {
		return fmt.Errorf("unknown server type %q", b.Type)
	}
	if b.Version == "" {
		return errors.New("version is required")
	}
	if b.MemoryMB <= 0 {
		return errors.New("memoryMB must be > 0")
	}
	if b.ServerJAR == "" {
		return errors.New("serverJAR is required")
	}
	return nil
}

// defaultBaseImage returns an appropriate JRE base for the given Minecraft version.
// Paper/Spigot 1.20+ require Java 21, 1.17-1.19 Java 17, older Java 8.
func defaultBaseImage(version string) string {
	major := parseMCMajor(version)
	switch {
	case major >= 120:
		return "eclipse-temurin:21-jre-alpine"
	case major >= 117:
		return "eclipse-temurin:17-jre-alpine"
	default:
		return "eclipse-temurin:8-jre-alpine"
	}
}

// parseMCMajor converts "1.20.4" -> 120, "1.8.8" -> 108, "1.21" -> 121.
// Returns 0 on parse failure.
func parseMCMajor(v string) int {
	parts := strings.Split(strings.TrimPrefix(v, "v"), ".")
	if len(parts) < 2 {
		return 0
	}
	var major, minor int
	_, err := fmt.Sscanf(parts[0], "%d", &major)
	if err != nil {
		return 0
	}
	_, err = fmt.Sscanf(parts[1], "%d", &minor)
	if err != nil {
		return 0
	}
	return major*100 + minor
}

const dockerfileTmpl = `# Auto-generated by mc-operator/pkg/mcimage
FROM {{.BaseImage}}

LABEL mc-operator.type="{{.Type}}"
LABEL mc-operator.version="{{.Version}}"

RUN mkdir -p /server/plugins /server/config /server/world
WORKDIR /server

COPY {{.ServerJAR}} /server/server.jar
{{range .PluginJARs}}COPY {{.}} /server/plugins/
{{end}}
{{range $dst, $src := .ExtraFiles}}COPY {{$src}} {{$dst}}
{{end}}

# EULA acceptance — required for vanilla/paper/spigot. Users must ensure they
# accept Mojang EULA terms when using this image.
RUN echo "eula=true" > /server/eula.txt

ENV MC_MEMORY_MB={{.MemoryMB}}

EXPOSE 25565
{{if eq (printf "%s" .Type) "velocity"}}EXPOSE 25577
{{end}}

ENTRYPOINT ["sh","-c","exec java -Xms${MC_MEMORY_MB}M -Xmx${MC_MEMORY_MB}M -jar /server/server.jar nogui"]
`

// RenderDockerfile returns the Dockerfile bytes for the given spec.
//
// Path normalization: Dockerfile COPY directives MUST use forward slashes
// even on Windows hosts, because Docker treats backslashes as escape
// characters (e.g. "jars\paper.jar" becomes "jarspaper.jar"). The build
// context tar also uses forward-slash entry names, so normalizing here
// keeps both sides consistent.
func RenderDockerfile(spec BuildSpec) ([]byte, error) {
	if err := spec.validate(); err != nil {
		return nil, err
	}
	if spec.BaseImage == "" {
		spec.BaseImage = defaultBaseImage(spec.Version)
	}
	spec.ServerJAR = filepath.ToSlash(spec.ServerJAR)
	for i, p := range spec.PluginJARs {
		spec.PluginJARs[i] = filepath.ToSlash(p)
	}
	normalizedExtras := make(map[string]string, len(spec.ExtraFiles))
	for dst, src := range spec.ExtraFiles {
		normalizedExtras[filepath.ToSlash(dst)] = filepath.ToSlash(src)
	}
	spec.ExtraFiles = normalizedExtras
	t, err := template.New("dockerfile").Parse(dockerfileTmpl)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, spec); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}
